# Generated by Django 5.0 on 2023-12-14 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=255, verbose_name='domain zone id')),
                ('data', models.TextField(blank=True, editable=False, null=True, verbose_name='داده ها')),
            ],
            options={
                'verbose_name': 'زون',
                'verbose_name_plural': 'زون ها',
            },
        ),
        migrations.CreateModel(
            name='DNSSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=255, verbose_name='record id')),
                ('dns_name', models.CharField(help_text='sample: app.dnsforyou.xyz', max_length=255, verbose_name='dns name')),
                ('dns_record_type', models.CharField(choices=[('A', 'A'), ('NS', 'NS'), ('MX', 'MX'), ('CNAME', 'CNAME')], max_length=255, verbose_name='dns record type')),
                ('dns_proxied', models.BooleanField(default=False, verbose_name='proxied')),
                ('current_ip', models.CharField(max_length=255, verbose_name='current ip')),
                ('ip_list', models.TextField(help_text='sample: 0.0.0.0,1.1.1.1,...', verbose_name='لیست ایپی ها')),
                ('sleep_time', models.PositiveIntegerField(default=60, verbose_name='زمان انتظار')),
                ('log', models.TextField(blank=True, editable=False, null=True, verbose_name='لاگ')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns_changer.zone', verbose_name='zone')),
            ],
            options={
                'verbose_name': 'تنظیم dns',
                'verbose_name_plural': 'تنظیم dns ها',
                'unique_together': {('zone', 'record_id')},
            },
        ),
    ]
